import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Usuario",
      email: "usuario@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "Camisa Deportiva Polo",
      slug: "polo-sporting-stretch-shirt",
      category: "Camisas de Vestir de Hombres",
      description: "Estilo Polo Clásico con confort moderno",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 59.99,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Camisa Brooks Brothers Manga Larga",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Camisas de Vestir de Hombres",
      description: "Estilo atemportal con confort premium",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Camisa de Vestir Clasica Tommy Hilfiger",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Camisas de Vestir de Hombres",
      description: "Una combinación perfecta de estilo y confort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Camisa Calvin Klein Slim",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Camisas de Vestir de Hombres",
      description: "Diseño rayado con flexible ajuste de fábrica",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Camisa Oxford Polo Ralph Lauren",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Camisas de Vestir de Hombres",
      description: "Diseño iconico Polo refinado en fábrica oxford",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Rosada",
      slug: "polo-classic-pink-hoodie",
      category: "Camisas de Vestir de Hombres",
      description: "Suave, con estilo, y perfecta para días de relajación",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
